Use labs for long types
Sample warning reported by clang:

elf32-arm.c:8827:10: error: absolute value function 'abs' given an argument
of type 'bfd_signed_vma' (aka 'long') but has parameter of type 'int' which
may cause truncation of value [-Werror,-Wabsolute-value]
        value = abs (relocation);
                ^
elf32-arm.c:8827:10: note: use function 'labs' instead
        value = abs (relocation);
                ^~~
                labs